default: &default
  adapter: redis
  url: redis://localhost:6379/1

development:
  <<: *default

test:
  <<: *default
  url: redis://localhost:6379/2

production:
  adapter: redis
  url: redis://localhost:6379/1
